// Generated by CoffeeScript 1.3.2-pre

module.exports = {
  abstracts: require('abstracts'),
  Model: require('Model'),
  Collection: require('Collection'),
  ActorModel: require('ActorModel'),
  RoomCollection: require('RoomCollection')
};
