// Generated by CoffeeScript 1.3.2-pre
var Collection, RoomCollection,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Collection = require('Collection');

RoomCollection = (function(_super) {

  __extends(RoomCollection, _super);

  function RoomCollection() {
    return RoomCollection.__super__.constructor.apply(this, arguments);
  }

  RoomCollection.prototype.propagate = function(action) {
    var _this = this;
    this.each(function(actor) {
      return actor.play(action);
    });
    return this.trigger('propagate', action);
  };

  return RoomCollection;

})(Collection);

module.exports = RoomCollection;
