// Generated by CoffeeScript 1.3.2-pre
var ActionAbstract, ObjectAbstract,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ObjectAbstract = require('ObjectAbstract');

ActionAbstract = (function(_super) {

  __extends(ActionAbstract, _super);

  function ActionAbstract() {
    return ActionAbstract.__super__.constructor.apply(this, arguments);
  }

  ActionAbstract.prototype.run = function(actor) {};

  return ActionAbstract;

})(ObjectAbstract);

module.exports = ActionAbstract;
