// Generated by CoffeeScript 1.3.2-pre
var ActorAbstract, ObjectAbstract,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ObjectAbstract = require('ObjectAbstract');

ActorAbstract = (function(_super) {

  __extends(ActorAbstract, _super);

  function ActorAbstract() {
    return ActorAbstract.__super__.constructor.apply(this, arguments);
  }

  ActorAbstract.prototype.play = function(action) {
    action.run(this);
    return this.trigger('play', action);
  };

  return ActorAbstract;

})(ObjectAbstract);

module.exports = ActorAbstract;
