// Generated by CoffeeScript 1.3.2-pre

module.exports = {
  ObjectAbstract: require('ObjectAbstract'),
  CollectionAbstract: require('CollectionAbstract'),
  RoomAbstract: require('RoomAbstract'),
  WorldAbstract: require('WorldAbstract'),
  ActionAbstract: require('ActionAbstract'),
  ActorAbstract: require('ActorAbstract')
};
