// Generated by CoffeeScript 1.3.2-pre
var CollectionAbstract, RoomAbstract,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CollectionAbstract = require('CollectionAbstract');

RoomAbstract = (function(_super) {

  __extends(RoomAbstract, _super);

  function RoomAbstract() {
    return RoomAbstract.__super__.constructor.apply(this, arguments);
  }

  RoomAbstract.prototype.propagate = function(action) {
    var _this = this;
    this.each(function(actor) {
      return actor.play(action);
    });
    return this.trigger('propagate', action);
  };

  return RoomAbstract;

})(CollectionAbstract);

module.exports = RoomAbstract;
