// Generated by CoffeeScript 1.3.2-pre
var CollectionAbstract, WorldAbstract,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CollectionAbstract = require('CollectionAbstract');

WorldAbstract = (function(_super) {

  __extends(WorldAbstract, _super);

  function WorldAbstract() {
    return WorldAbstract.__super__.constructor.apply(this, arguments);
  }

  WorldAbstract.prototype.propagate = function(action) {
    var _this = this;
    this.each(function(space) {
      return space.propagate(action);
    });
    return this.trigger('propagate', action);
  };

  return WorldAbstract;

})(CollectionAbstract);

module.exports = WorldAbstract;
